### ISSUE TITLE
Finding the file associated with the SATD commit label

### ISSUE THREAD

**Issue by shehan** [smartshark/smartshark.github.io#24]
Is there a way to determine the source file(s) associated with the commit that has the labels "_documentation_technicaldept_add_" or "_documentation_technicaldept_remove_"

I can only think of analyzing the hunk for the presence of the SADT keywords, but this can be performance-intensive. Is there a more optimized approach (i.e., without any regex/nlp)?

**Comment by atrautsch** [comment]
No there is no other way. The labels are only at the commit level further analysis is required to find single files.

**Comment by shehan** [comment]
Thanks for the quick reply.
