### ISSUE TITLE
Duplicates in the refactoring collection?

### ISSUE THREAD

**Issue by shehan** [smartshark/smartshark.github.io#25]
I understand that the tools rMiner and refDiff were utilized to mine refactoring operations in the code.
Since these two tools overlap in the type of refactoring operations they detect, I need to know if I need to perform duplicate checks when querying the 'refactoring' collection.

For example, in File A, a rename method operation was applied to method ABC(). Are there duplicate entries in the 'refactoring' collection - one for rMiner and one for refDiff? Or is this refactoring instance only captured once in the 'refactoring' collection?

Thanks!

**Comment by shehan** [comment]
Exploring the data, I'm encountering _some_ instances of duplication. Examples:

- refactoring id: 5ca0f047bf0c4e088bf00f59 and 5e2825547e171b13bc26de5d
- refactoring id: 5ca0eefaabbb987cd32a7aef and 5e2825567e171b13bc26e6b3 
- refactoring id: 5ca0eefaabbb987cd32a7af0 and 5e2825567e171b13bc26e6b4

**Comment by atrautsch** [comment]
There is a detection_tool field for each document in the refactoring collection which indicates which refactoring detection tool reported the refactoring.
