### ISSUE TITLE
Missing commit id in travis_build

### ISSUE THREAD

**Issue by oathaha** [smartshark/smartshark.github.io#26]
I saw in smartSHARK database schema figure that travis_build entity has commit id link to commit entity. However, when I looked at travis_build in the website, I did not find commit id column like in the mentioned figure. So I am not sure if the explanation in website or the figure is not correct. Please clarify this issue.

**Comment by atrautsch** [comment]
Thank you for opening the issue, it seems that the website is missing this information.
We will update the website in the next days. TravisBuild has indeed a commit_id, you can also see this in the [model definition](https://github.com/smartshark/pycoSHARK/blob/master/pycoshark/mongomodels.py).

**Comment by oathaha** [comment]
Thank you for your clarification.
