### ISSUE TITLE
Update to the Data Releases page on the website

### ISSUE THREAD

**Issue by shehan** [smartshark/smartshark.github.io#30]
I restored Release 2.2 Full Version, and the volume of disk space taken by the database is 728.276GB. However, the [webpage](https://smartshark.github.io/dbreleases/) shows 640GB. I ran into disk space issues since I had provisioned my VM by considering the 640GB value on the website. 

I recommend changing 640GB to 740GB on the website.

**Comment by atrautsch** [comment]
Strange, maybe there are some differences between MongoDB versions, storage backends or file systems. I have increased the file size to 740GB now.
