### ISSUE TITLE
add new travis specific dockerfile to each plugin 

### ISSUE THREAD

**Issue by ftrautsch** [smartshark/smartshark.github.io#9]
Currently, we only have one Dockerfile for each project. The problem is that in these Dockerfiles we always clone the master branch of the repository. This is problematic for pull requests: If we get a new pull request that should be directly tested via Travis, we currently clone the master branch test it instead of the pull request.

Hence, we should add a new Travis specific Dockerfile and Travis should be configured in a way that it uses this Dockerfile instead.

**Comment by sherbold** [comment]
Instead of this, we will move to travis builds that do not rely on Docker. Examples can already be found in the labelSHARK, the linkSHARK and the memeSHARK
